//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FouziaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class appealCouncilOfState_tbl
    {
        public int appealID { get; set; }
        public Nullable<System.DateTime> dateOfAppeal { get; set; }
        public Nullable<int> appealNum { get; set; }
        public Nullable<System.DateTime> dateOfReport { get; set; }
        public Nullable<int> reportNum { get; set; }
        public string judgmentOfAppeal { get; set; }
        public Nullable<int> caseID { get; set; }
    
        public virtual case_tbl case_tbl { get; set; }
    }
}
