//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FouziaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class case_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public case_tbl()
        {
            this.appealCouncilOfState_tbl = new HashSet<appealCouncilOfState_tbl>();
            this.appealSupremeCourt_tbl = new HashSet<appealSupremeCourt_tbl>();
        }
    
        public int caseID { get; set; }
        public Nullable<int> caseNum { get; set; }
        public Nullable<System.DateTime> dateOfTheOpenPetition { get; set; }
        public Nullable<System.DateTime> dateOfTheReply { get; set; }
        public Nullable<System.DateTime> dateOfTheJudgment { get; set; }
        public string judgment { get; set; }
        public Nullable<bool> finished { get; set; }
        public Nullable<System.DateTime> dateOfTheExpertsCall { get; set; }
        public Nullable<System.DateTime> dateOfReplyToTheExpert { get; set; }
        public Nullable<int> csID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public Nullable<int> rcID { get; set; }
        public string filePath { get; set; }
        public Nullable<int> JOCID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appealCouncilOfState_tbl> appealCouncilOfState_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appealSupremeCourt_tbl> appealSupremeCourt_tbl { get; set; }
        public virtual caseSubject_tbl caseSubject_tbl { get; set; }
        public virtual judgmentOnTheCase_tbl judgmentOnTheCase_tbl { get; set; }
        public virtual receiptOfCase_tbl receiptOfCase_tbl { get; set; }
        public virtual service_tbl service_tbl { get; set; }
    }
}
