//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FouziaApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fouziaDBEntities : DbContext
    {
        public fouziaDBEntities()
            : base("name=fouziaDBEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<appealCouncilOfState_tbl> appealCouncilOfState_tbl { get; set; }
        public virtual DbSet<appealSupremeCourt_tbl> appealSupremeCourt_tbl { get; set; }
        public virtual DbSet<case_tbl> case_tbl { get; set; }
        public virtual DbSet<caseSubject_tbl> caseSubject_tbl { get; set; }
        public virtual DbSet<catSub_tbl> catSub_tbl { get; set; }
        public virtual DbSet<judgmentOnTheCase_tbl> judgmentOnTheCase_tbl { get; set; }
        public virtual DbSet<partiesToTheConflict_tbl> partiesToTheConflict_tbl { get; set; }
        public virtual DbSet<persons_tbl> persons_tbl { get; set; }
        public virtual DbSet<receiptOfCase_tbl> receiptOfCase_tbl { get; set; }
        public virtual DbSet<record_tbl> record_tbl { get; set; }
        public virtual DbSet<service_tbl> service_tbl { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
