//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FouziaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class persons_tbl
    {
        public int personID { get; set; }
        public string personName { get; set; }
        public Nullable<int> PTCID { get; set; }
        public Nullable<int> csID { get; set; }
    
        public virtual caseSubject_tbl caseSubject_tbl { get; set; }
        public virtual partiesToTheConflict_tbl partiesToTheConflict_tbl { get; set; }
    }
}
